// 이 프로그램은 무조건 실패한다.
// 왜냐하면
fn main() {
    let x = 5;
    println!("The value of x is: {}", x);
    x = 6;
    println!("The value of x is: {}", x);
}
